"""Initial migration with UserModel and ProfileModel tables

Revision ID: 6707b7c73d4b
Revises: 
Create Date: 2025-06-16 12:55:18.186510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6707b7c73d4b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profilemodel',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), server_default='', nullable=False),
    sa.Column('registration_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('taps_statistics', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('about', sa.String(length=500), server_default='', nullable=False),
    sa.Column('photo', sa.String(length=255), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('client_id', name=op.f('pk_profilemodel')),
    sa.UniqueConstraint('client_id', name=op.f('uq_profilemodel_client_id'))
    )
    op.create_table('usermodel',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('access', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['profilemodel.client_id'], name=op.f('fk_usermodel_client_id_profilemodel'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id', name=op.f('pk_usermodel')),
    sa.UniqueConstraint('client_id', name=op.f('uq_usermodel_client_id'))
    )
    op.create_index(op.f('ix_usermodel_username'), 'usermodel', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usermodel_username'), table_name='usermodel')
    op.drop_table('usermodel')
    op.drop_table('profilemodel')
    # ### end Alembic commands ###
